/* eslint-disable @next/next/no-img-element */
import type { NextPage } from "next";
import { signIn, signOut, useSession } from "next-auth/react";
import Head from "next/head";

const Home: NextPage = () => {
    const { data: session } = useSession();

  return (
    <>
      <Head>
        <title>AnimeList</title>
        <meta name="description" content="Generated by create-t3-app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <main className="container mx-auto flex flex-col items-center justify-center min-h-screen p-4">
        <h1 className="text-5xl md:text-[5rem] font-extrabold text-gray-700">
          Anime<span className="text-red-500">List</span>
        </h1>
        {session?.user && (
            <div className="flex items-center gap-2">
                <h1>Signed in as <span className="text-red-500">{session.user.email}</span></h1>
                <img className="w-16 h-16 rounded-full" src={session.user.image ?? ''} alt='' />
            </div>
        )}
        <Button/>
      </main>
    </>
  );
};

const Button = () => {
    const { data: session } = useSession();

    const buttonAction = () => {
        if(session) {
            signOut();
            return;
        }

        signIn();
    };

    const buttonText = session ? 'Sign out' : 'Sign in';

    return (
        <button 
        className="border-2 border-solid border-red-500 rounded-xl p-2 m-2"
         onClick={buttonAction}>
            {buttonText}
         </button>
    )
}

export default Home;
